### ISSUE TITLE
early input on stdin causes "Bad file descriptor" error

### ISSUE THREAD

**Issue by etuttle** [brandond/aws-acl-helper#2]
The asyncio module raises "Bad file descriptor" if there is data ready on stdin before read/write pipes are setup.

```
Fatal read error on pipe transport
protocol: <asyncio.streams.StreamReaderProtocol object at 0x7fc2e3e15588>
transport: <_UnixReadPipeTransport fd=0 polling>
Traceback (most recent call last):
  File "/usr/lib64/python3.5/asyncio/unix_events.py", line 381, in _read_ready
    data = os.read(self._fileno, self.max_size)
OSError: [Errno 9] Bad file descriptor
```

If squid has work queued for the helper, this can result in a crash loop and squid eventually dying with "helpers are crashing too rapidly, need help!".  I'm including a repro script below.

I tried to tweak the code in aws-acl-helper `stdio()` to fix it.  Connecting the read pipe before the write pipe fixes the early input error, but then the write pipe ends up closed after one message exchange.

The proper solution may be an asyncio protocol (akin to `SubprocessStreamProtocol`) that supports connecting StreamReader/StreamWriter to stdio (see [message thread](https://groups.google.com/forum/#!topic/python-tulip/6tRswyRhwE4)).  But I can't find an existing implementation.

I have a work-around that involves accepting stdin as a bidirectional socket with squid.  I'll open a PR when it is more thoroughly tested.

```
#!/usr/bin/python35

import os
import socket
import sys
import time

SLOW_START = False

# emulate squid: setup a tcp socket pair, make it stdin/stdout for a helper

# parent socket
ps = socket.socket(socket.AF_INET, socket.SOCK_STREAM)

# child listener socket
cls = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
cls.bind(('127.0.0.1', 0))
_, port = cls.getsockname()
cls.listen(1)

if os.fork() != 0:
    # parent
    ps.connect(('127.0.0.1', port))
    reader = ps.makefile('r')
    if SLOW_START:
        time.sleep(1)
    while True:
        send = '10000 1.1.1.1 tag:test'
        print("SEND: %s" % send, file=sys.stderr, flush=True)
        ps.sendall(bytes(send + "\n", encoding='ascii'))
        resp = reader.readline()
        print("RECV: %s" % resp.strip(), file=sys.stderr, flush=True)
        time.sleep(0.5)
else:
    # child
    cs, _ = cls.accept()

    t1 = os.dup(cs.fileno())
    t2 = os.dup(cs.fileno())
    os.close(cs.fileno())
    os.dup2(t1, 0)
    os.dup2(t2, 1)
    os.close(t1)
    os.close(t2)

    os.execv('/usr/local/bin/aws-acl-helper', ['aws-acl-helper', 'listen'])
```

**Comment by brandond** [comment]
Thanks for the patch @etuttle! Which version of Squid were you seeing this with?

**Comment by etuttle** [comment]
Hi @brandond , no problem, thanks for writing this thing in the first place.

I saw the crash under squid 4.0.21, the only version I've run the helper with.
